let recordType = {
    CLASS_PERFORMANCE_EVALUATION: 'CLASS_PERFORMANCE_EVALUATION',
    SELF_KEYWORD: 'SELF_KEYWORD',
    RECOMMEND_BOOK: 'RECOMMEND_BOOK',
    TEACHER_EVALUATION: 'TEACHER_EVALUATION',
    WONDERFUL_MOMENT: 'WONDERFUL_MOMENT',
    SHARE_IMG: 'SHARE_IMG'
}

export default recordType